version:  '3.7'

services:
  mysql:
    image: mysql:5.7.29
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_cms
    volumes:
      - db-data:/var/lib/mysql
    ports: 
      - "3307:3306"

  web:
    build: web
    ports: 
      - "8080:80"
    volumes: 
      - ./app:/var/www
    depends_on: 
      - mysql
      - php-fpm
  
  php-fpm:
    build: php-fpm
    expose:
      - 9000
    volumes:
        - ./app:/var/www
        - ./GregwarCaptchaExtensionBundle:/var/GregwarCaptchaExtensionBundle
        - ./TestFixtures:/var/TestFixtures
        - ./TestUtils:/var/TestUtils
        - ./php-fpm/config.json:/root/.config/composer/config.json
    depends_on:
      - mysql
  
  node:
    image: node:16.3.0-buster
    command: bash -c "yarn install && yarn encore dev --watch"
    working_dir: /var/www
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www

volumes: 
  db-data: {}