version:  '3.7'

services:
  mysql:
    image: mysql:5.7.29
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_cms
    volumes:
      - db-data:/var/lib/mysql
    ports: 
      - 3307:3306

  web:
    build: web
    ports: 
      - 8080:80
    volumes: 
      - ./app:/var/www
    depends_on: 
      - mysql
      - php73
  
  php73:
    build: php73
    expose:
      - 9000
    volumes:
        - ./app:/var/www
    depends_on: 
      - mysql

  composer-installer:
    image: composer:2.0
    working_dir: /var/www
    volumes:
      - ./app:/var/www
  
  node:
    image: node:16.3.0-buster
    command: bash -c "ls -l && yarn install && yarn encore dev --watch"
    working_dir: /var/www
    ports:
      - 3000:3000
    volumes:
      - ./app:/var/www

volumes: 
  db-data: {}